# Generated by Django 4.2.6 on 2024-12-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='store',
            name='jam_buka',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='jam_tutup',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='nomor_telepon',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
