# Generated by Django 5.1.2 on 2024-10-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_alter_review_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
