# Generated by Django 5.1.2 on 2024-10-26 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_username'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_profile', models.ForeignKey(blank=True, help_text='Only buyers can have additional profiles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_profiles', to='user.userprofile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='authentication.profile')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
