# Generated by Django 5.1.2 on 2024-10-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image_link', models.CharField(max_length=255)),
                ('spec', models.CharField(max_length=255)),
            ],
        ),
    ]
