# Generated by Django 5.1.2 on 2024-10-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='image_link',
            field=models.ImageField(upload_to=''),
        ),
    ]
