# Generated by Django 4.2.6 on 2024-10-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_katalog_image_link_alter_katalog_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='store',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
