# Generated by Django 5.1.2 on 2024-10-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_katalog_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='spec',
            field=models.CharField(max_length=512),
        ),
    ]
