# Generated by Django 4.2.6 on 2024-10-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_katalog_image_link'),
        ('products', '0005_remove_katalog_store_delete_store'),
    ]

    operations = [
    ]
