# Generated by Django 4.2.6 on 2024-10-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_katalog_price_alter_katalog_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='image_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='spec',
            field=models.CharField(max_length=255),
        ),
    ]
