# Generated by Django 5.1.2 on 2024-10-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_katalog_spec'),
        ('products', '0007_alter_katalog_price_alter_katalog_spec'),
    ]

    operations = [
    ]
