# Generated by Django 5.1.2 on 2024-10-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20241025_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
