# Generated by Django 4.2.6 on 2024-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_katalog_id_alter_katalog_image_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='spec',
            field=models.CharField(max_length=512),
        ),
    ]
