# Generated by Django 4.2.6 on 2024-10-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_katalog_id'),
        ('products', '0009_alter_katalog_spec'),
    ]

    operations = [
    ]
