# Generated by Django 4.2.6 on 2024-10-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_id'),
        ('products', '0010_merge_0009_alter_katalog_id_0009_alter_katalog_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
    ]
