# Generated by Django 5.1.1 on 2024-10-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_katalog_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='store',
        ),
    ]
